config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'create_user_post'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post'

  # Custom routes for likes
  get '/users/:user_id/posts/:post_id/likes/new', to: 'likes#new', as: 'new_post_like'
  post '/users/:user_id/posts/:post_id', to: 'likes#create', as: 'post_likes'
  delete '/users/:user_id/posts/:post_id/likes/:id', to: 'likes#destroy', as: 'post_like'

  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'create_post_comment'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'destroy_post_comment'


    namespace :api do
      namespace :v1 do
        resources :users do
          get 'posts', to: 'posts#index'
          resources :posts do
            get 'comments', to: 'comments#index'
            resources :comments, only: [:create]
          end
        end
      end
    end




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :authored_posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :post_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin' # self.role == 'admin'
  end

  def author?
    role == 'author' # self.role == 'author'
  end

  def user?
    role == 'user' # self.role == 'user'
  end

  def recent_posts(limit = 3)
    authored_posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_posts = Post.where(author_id: @user.id)
    @user_recent_posts = @user.recent_posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="users">

    <ul class="users-list">
    <% @users.each do |user| %>
       
        <li class="user-card">
            <div class="img-holder">
                <% if user.photo %>
                <%= image_tag user.photo, class: "user-img" %>
                <% else %>
                <%= image_tag "default.png", class: "user-img"%>
                <% end %>
            </div>
            <div class="card-details">
            <h4 class="user-name">
             <a href="<%= user_path(user) %>">
                <%= user.name %>
             </a>
            </h4>
             
            <p class="num-of-posts">Number of posts: <%= user.post_count %></p>
            </div>
        </li>
       
        <br/>
    <% end %>
    </ul>
    
</div>

app/views/users/show.html.erb
<ul class="user-list">
    <li class="user-card">
        <div class="img-holder">
            <% if @user.photo %>
                <%= image_tag @user.photo, class: "user-img" %>
                <% else %>
                <%= image_tag "default.png", class: "user-img"%>
            <% end %>
        </div>
        <div class="card-details">
        <h4 class="user-name"><%= @user.name %></h4>
        <p class="num-of-posts">Number of posts : <%= @user.post_count %></p>
        </div>
    </li>
    <br/>
    <li class="user-card">
        Bio
        <p class="bio"><%= @user.bio %></p>
        </div>
    </li>
    <% @user_recent_posts.each do |post| %>
        <li class="user-card">
            <div class="post-details">
            <h6 class="post-title"><%= post.title %></h6>
            <p class="post-brief"><%= post.text %></p>
            <p class="num-of-posts">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
            </div>
        </li>
    <br/>
    <% end %>
</ul>
<%= link_to user_posts_path(@user), class: 'button' do %>
  Show All
<% end %>