config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'
  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'create_user_post'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post'

  # Custom routes for likes
  get '/users/:user_id/posts/:post_id/likes/new', to: 'likes#new', as: 'new_post_like'
  post '/users/:user_id/posts/:post_id', to: 'likes#create', as: 'post_likes'
  delete '/users/:user_id/posts/:post_id/likes/:id', to: 'likes#destroy', as: 'post_like'

  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'create_post_comment'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy', as: 'destroy_post_comment'


    namespace :api do
      namespace :v1 do
        resources :users do
          get 'posts', to: 'posts#index'
          resources :posts do
            get 'comments', to: 'comments#index'
            resources :comments, only: [:create]
          end
        end
      end
    end




end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # Method to return the 5 most recent comments for a given post
  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def liked_by?(user)
    likes.exists?(user:)
  end

  after_initialize :set_defaults

  def set_defaults
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
  # Method to update the likes counter for a post

  after_save :update_user_posts_counter

  private

  def update_user_posts_counter
    author.update(post_count: author.authored_posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        user = User.find(params[:user_id])
        posts = user.authored_posts
        render json: posts
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:authored_posts).find(params[:user_id])
    @user_posts = @user.authored_posts

    render json: @user_posts
  end

  def like
    @post = Post.find(params[:id]) # Assuming you're using post_id in the route
    @like = @post.likes.build(user: @user)

    if @like.save
      flash[:success] = 'You liked this post.'
    else
      flash[:error] = 'Failed to like the post.'
    end

    redirect_to @post
  end

  def new
    @user = User.find(params[:user_id])
    @user_posts = Post.where(author_id: @user.id)
    @user_post = Post.new

    respond_to do |format|
      format.html { render :new, locals: { user_post: @user_post } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    post = @user.authored_posts.build(post_params)
    authorize! :manage, @post

    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_path(@user)
        else
          flash[:error] = 'not created'

          render :new, locals: { user_post: post }
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post

    @user = @post.author

    @post.likes.destroy_all
    @post.comments.destroy_all

    redirect_to user_posts_path(user_id: @user.id)
    if @post.destroy
      flash[:success] = 'Post deleted successfully'

    else
      flash[:error] = 'Failed to delete the post'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @user_posts = Post.where(author_id: @user.id)
    @user_post = Post.find(params[:id])

    render json: @user_post
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<ul class="user-posts-list">
    <li class="user-card">
        <div class="img-holder">
            <% if @user.photo %>
                <%= image_tag @user.photo, class: "user-img"%>
                <% else %>
                <%= image_tag "default.png", class: "user-img"%>
            <% end %>
        </div>
        <div class="card-details">
        <h4 class="user-name"><%= @user.name %></h4>
        <p class="num-of-posts">Number of posts : <%= @user.post_count %></p>
        </div>
    </li>
    <% @user_posts.each do |post| %>
    <li class="user-card">
       
            <div class="card-details">
                <h6 class="post-title">
                    <a href="<%= user_post_path(@user, post) %>">  
                        <%= post.title %></h6>
                    </a>
                <p class="post-brief"><%= post.text %></p>
                <p class="num-of-posts">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
              
            </div>
        
        <%= button_to "Like", post_likes_path(user_id: post.author_id, post_id: post.id), method: :post, class: 'like-button' %>
        <% if can? :destroy, post %>
            <%= link_to 'Delete', destroy_user_post_path(user_id: post.author_id, id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>

    </li>
      <% if !post.comments.empty? %>
        <div class="comments-card">
            <% post.recent_comments.each do |comment| %>
                <% user = User.find(comment.user_id) %>
                <p class="post-brief"><strong><%= user.name%>:</strong> <%= comment.text %></p>
                <% if can? :destroy, comment %>
                    <%= link_to "delete", destroy_post_comment_path(user_id: @user, post_id: post, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
            <% end %>
           
        </div>
      <% end %>
    <br/>
    <% end %>
</ul>
<div class="d-grid gap-2 w-25 m-auto">
<% if can? :create, @post %>
    <%= link_to 'Add Post', new_user_post_path, class: 'btn btn-primary' %> 
<% end %>
<%= link_to user_posts_path(@user), class: 'btn btn-primary' do %>
  Show all posts
<% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: Post.new, url: user_posts_path(current_user), method: :post, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.hidden_field :author_id, value: current_user.id %>

  <%= f.submit "Create Post" %>
<% end %>

<%= link_to "Back", user_posts_path %>
<%= flash[:error] %><%= flash[:success] %>

app/views/posts/show.html.erb
<section class="user-post">
    <div class="post-content">
        <% user = User.find(@user_post.author_id) %>
        <p class="post-stats"><span><%= @user_post.title %> by <strong><%= user.name %></strong> </span><span>Comments: <%= @user_post.comments_counter %>, Likes: <%= @user_post.likes_counter %></span></p>
        <p><%= @user_post.text %></p>
        <%= link_to "Like", post_likes_path(user_id: @user_post.author_id, post_id: @user_post.id), method: :post, class: 'btn btn-outline-warning' %>
        <% if can? :destroy, @user_post %>
             <%= link_to 'Delete', destroy_user_post_path(@user_post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
    <% if !@user_post.comments.empty? %>
        <div class="comments-card">
            <% @user_post.comments.each do |comment| %>
                <% user = current_user %>
                <p class="post-brief"><strong><%= user.name%>:</strong> <%= comment.text %></p>
                <% if can? :destroy, comment %>
                    <%= link_to 'Delete', destroy_post_comment_path(user_id: @user_post.author_id, post_id: @user_post.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>
            <% end %>
        </div>
    <% end %>
</section>
<div class="w-25 m-auto">
<%= link_to "Add Comment", new_user_post_comment_path(user_id: @user.id, post_id: @post.id), class: "btn btn-primary w-75 m-auto" %>
</div>